spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
server:
  port: 8080
  servlet:
    context-path: /auth
logging:
  level:
    org.*: info
springfox:
  swagger:
    host: 8080
